print("Hello world - from Group 5")
print("Member 1: Manuba - Backend")
print("Member 2: Lugo - Frontend")
print("Member 3: David - Tester")
print("Member 4: Punzalan - Tester")
print("Member 5: Pagayao - Tester")
print("Member 6: Villanueva - Frontend")